// <auto-generated />
using System;
using Blog_Barneaud_Huyghe.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Blog_Barneaud_Huyghe.Migrations
{
    [DbContext(typeof(ArticleDbContext))]
    partial class ArticleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Blog_Barneaud_Huyghe.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IndividuId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Publication")
                        .HasColumnType("datetime2");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("IndividuId");

                    b.ToTable("Article");
                });

            modelBuilder.Entity("Blog_Barneaud_Huyghe.Models.Commentaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<bool>("Autorisation")
                        .HasColumnType("bit");

                    b.Property<int>("IndividuId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("Publication")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IndividuId");

                    b.ToTable("Commentaire");
                });

            modelBuilder.Entity("Blog_Barneaud_Huyghe.Models.Individu", b =>
                {
                    b.Property<int>("IndividuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("EstBloggeur")
                        .HasColumnType("bit");

                    b.Property<string>("Identifiant")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Motdepasse")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("IndividuId");

                    b.ToTable("Individu");
                });

            modelBuilder.Entity("Blog_Barneaud_Huyghe.Models.Article", b =>
                {
                    b.HasOne("Blog_Barneaud_Huyghe.Models.Individu", "ArticleIndividuId")
                        .WithMany()
                        .HasForeignKey("IndividuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArticleIndividuId");
                });

            modelBuilder.Entity("Blog_Barneaud_Huyghe.Models.Commentaire", b =>
                {
                    b.HasOne("Blog_Barneaud_Huyghe.Models.Individu", "CommentaireIndividuId")
                        .WithMany()
                        .HasForeignKey("IndividuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommentaireIndividuId");
                });
#pragma warning restore 612, 618
        }
    }
}
